Cybersecurity is the ongoing effort to protect network system and its data from unauthorized use or harm.
Your Data includes; Medical data, Employment, Information online, Your identity, Education Data, Financial Data, Data on your computing devices.
Corporate data includes personal information, intellectual properties and financial data.
Personnel information includes payroll, employee agreement, offer letters, application materials and any other materials used in making employment decisions.
Intellectual properties allows a business to gain economic advantage over its competitors and they are patent, trademarks, new product plan, etc. This property is also considered a trade secret and losing this information can be disastrous for the future of the company.
Financial data gives an insight into the health of the company. It includes; Balance sheet, income statements and cash flow statement of a company.
Internet of Things(IoT) is a large network of physical objects, such as sensors and equipment that extend beyond the traditional computer network.
The exponential growth of data through this means including expansion in storage services and capacity through the cloud and virtualization led to the creation of a new area of interest in technology and business called Big Data.
Confidentiality, Integrity and Availability(CIA) Triad is a guideline for information security in an organization.
Confidentiality ensures the privacy of data by restricting access through authentication encryption.
Integrity assures that the information is accurate and trustworthy.
Availability ensures that the information is accessible to authorized persons.
Checksum is used to verify the integrity of files, or strings of characters after they have been transferred from one device to another across your local network or the internet. Checksums are calculated with hash functions. Some of the common checksums are MD5, SHA-1, SHA-256, and SHA-512
A hash function uses a mathematical algorithm to transform the data into a fixed length value that represents the data. From the hashed value, the original value cannot be retrieved directly. After a file is downloaded, you can verify its integrity by verifying the hash values from the source with the one you generated using any hash calculator. By comparing the hash values, you can ensure that the file has not been tampered with or corrupted during the transfer. (Integrity)
NB: Hash types creates different length of hash because a larger bit hash can provide more security because there are more possible combination.
Denial of Service(DoS) occurs when an attacker attempts to overwhelm resources so the services are not available to the users(Availability)
Security breaches occur when individuals or applications are trying to gain unauthorized access to data, applications, services, or devices. During these breaches, the attackers, whether they are insiders or not, attempt to obtain information that they could use for financial gains or other advantages.
Consequences of a security Breach includes; Ruined reputation, Vandalism, Theft, Revenue lost, Damaged intellectual property.
Cyber attackers are individuals or groups who attempt to exploit vulnerability for personal or financial gain. We have different types of attackers which are;
Amateurs: These are often called script kiddies, they are attackers who have little or no skill usually using tools found on the internet or existing tools or instructions to launch attacks. This might be out of curiosity or trying to demonstrate their skills thereby causing harm.
Hackers: These are group of attackers that break into computers or network to gain access. These break in is dependent on the class of hacker, we have the White, Black or Gray hat Hackers.
White Hat Hackers are ethical hackers who use their programming skills for good ethical, and legal purposes. White Hat Hackers break into computers or networks to discover its weakness to improve it, these break ins are done with prior permission from owners are results are reported back to owners.
Black Hat Hackers are unethical criminals who violate computer and network security for personal gain, or for malicious reasons such as attacking networks. Black Hat Hackers take advantage of vulnerability for their personal, financial or political gain.
Gray Hat Hackers are individuals who commit crimes and do unethical things, but not for personal gain. Gray Hat Hackers are in between white and black hat hackers, some may report vulnerability to the owners if that action coincides with their agenda while some others will publish the vulnerability on the internet for other attackers to exploit.
Organized Hackers includes cyber criminals, hacktivists, terrorist and state sponsored hackers. Cyber criminals are usually groups of professional criminals focused on control, power, and wealth. The criminals are highly sophisticated and organized, and they may even provide cybercrime as a service to other criminals. Hacktivists make political statements to create awareness to issues that are important to them. State-sponsored attackers gather intelligence or commit sabotage on behalf of their government. These attackers are usually highly trained and well-funded, and their attacks are focused on specific goals that are beneficial to their government.
Cyber attackers can be internal, i.e; Inside the organization or External, i.e outside the organization. Internal security comprises of Employees, Contract staff and Trusted partners whereas External security threat comprises of organized attackers, hackers and amateurs.
Cybersecurity professionals must have the same skills as the cyber attackers. Cybersecurity professionals must work within the bounds of the local, national and international law. Cybersecurity professionals must also use their skills ethically.
Cyberwarfare is an internet based conflict that involves the penetration of computer systems and network of other nations. These warfare can carry out conflicts without the clashes of traditional troops and machines, these attackers have the expertise and resources to launch massive internet based attacks against other nations to cause damage or disrupt services, such as shutting down a power grid. An example is Stuxnet malware that was designed to damage Iran nuclear enrichment, it was designed to damage physical equipment that was controlled by computers. It used modular coding that was programmed to perform a specific task within the malware. It has the ability to switch off oil pipelines, centrifuges that spin nuclear material. It does not borrow clearance like any other malware, it has a real clearance. Without its target, the virus remains dormant. Its a weapon that was made out of code.
Cyberwarfare can destabilize a nation, disrupt commerce, and affect the citizens’ faith in their government without ever physically invading the targeted nation.
Stuxnet is a malware program designed to damage the nuclear enrichment plant of Iran, a program which is an example of a state-sponsoredattack.
International Multilateral Partnership Against Cyber Threats (IMPACT)is a global partnership of world governments, industries, and academia dedicated to improving global capabilities when dealing with cyber threats.
Ethics are codes of behavior that are sometimes, but not always, enforced by laws.